-- Agentic AI Business Decision System Database Schema

-- Drop existing tables if they exist
DROP TABLE IF EXISTS agent_communications CASCADE;
DROP TABLE IF EXISTS agent_activities CASCADE;
DROP TABLE IF EXISTS decisions CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS metrics CASCADE;

-- Drop existing types
DROP TYPE IF EXISTS agent_type CASCADE;
DROP TYPE IF EXISTS decision_status CASCADE;
DROP TYPE IF EXISTS alert_severity CASCADE;
DROP TYPE IF EXISTS metric_type CASCADE;

-- Create enum types
CREATE TYPE metric_type AS ENUM (
    'revenue',
    'orders', 
    'churn_risk',
    'delivery_delay',
    'customer_satisfaction',
    'avg_order_value'
);

CREATE TYPE alert_severity AS ENUM (
    'low',
    'medium', 
    'high',
    'critical'
);

CREATE TYPE decision_status AS ENUM (
    'pending',
    'approved',
    'rejected', 
    'executed'
);

CREATE TYPE agent_type AS ENUM (
    'observer',
    'analyst',
    'simulation',
    'decision',
    'governance'
);

-- Metrics table - stores all business metrics over time
CREATE TABLE metrics (
    id SERIAL PRIMARY KEY,
    metric_type metric_type NOT NULL,
    value DECIMAL(15,4) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for metrics
CREATE INDEX idx_metrics_type_timestamp ON metrics(metric_type, timestamp DESC);
CREATE INDEX idx_metrics_timestamp ON metrics(timestamp DESC);
CREATE INDEX idx_metrics_created_at ON metrics(created_at DESC);

-- Alerts table - stores alerts generated by agents
CREATE TABLE alerts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    severity alert_severity NOT NULL,
    metric_type metric_type NOT NULL,
    threshold_value DECIMAL(15,4),
    current_value DECIMAL(15,4),
    agent_type agent_type NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    resolved_at TIMESTAMP WITH TIME ZONE,
    metadata JSONB DEFAULT '{}'
);

-- Indexes for alerts
CREATE INDEX idx_alerts_severity ON alerts(severity);
CREATE INDEX idx_alerts_created_at ON alerts(created_at DESC);
CREATE INDEX idx_alerts_agent_type ON alerts(agent_type);
CREATE INDEX idx_alerts_metric_type ON alerts(metric_type);
CREATE INDEX idx_alerts_unresolved ON alerts(resolved_at) WHERE resolved_at IS NULL;

-- Decisions table - stores AI decisions and their outcomes
CREATE TABLE decisions (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    scenarios JSONB NOT NULL DEFAULT '[]',
    recommended_scenario VARCHAR(255) NOT NULL,
    confidence_score DECIMAL(4,3) NOT NULL CHECK (confidence_score >= 0 AND confidence_score <= 1),
    financial_impact DECIMAL(15,2) NOT NULL,
    requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
    reasoning TEXT NOT NULL,
    status decision_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    approved_at TIMESTAMP WITH TIME ZONE,
    executed_at TIMESTAMP WITH TIME ZONE,
    approved_by VARCHAR(255),
    execution_result JSONB DEFAULT '{}',
    metadata JSONB DEFAULT '{}'
);

-- Indexes for decisions
CREATE INDEX idx_decisions_status ON decisions(status);
CREATE INDEX idx_decisions_created_at ON decisions(created_at DESC);
CREATE INDEX idx_decisions_requires_approval ON decisions(requires_approval);
CREATE INDEX idx_decisions_confidence ON decisions(confidence_score DESC);
CREATE INDEX idx_decisions_financial_impact ON decisions(ABS(financial_impact) DESC);

-- Agent activities table - logs all agent activities
CREATE TABLE agent_activities (
    id SERIAL PRIMARY KEY,
    agent_type agent_type NOT NULL,
    activity_type VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    data JSONB DEFAULT '{}',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    duration_ms INTEGER,
    success BOOLEAN DEFAULT TRUE,
    error_message TEXT
);

-- Indexes for agent activities
CREATE INDEX idx_agent_activities_type_timestamp ON agent_activities(agent_type, timestamp DESC);
CREATE INDEX idx_agent_activities_activity_type ON agent_activities(activity_type);
CREATE INDEX idx_agent_activities_success ON agent_activities(success);

-- Agent communications table - stores inter-agent messages
CREATE TABLE agent_communications (
    id SERIAL PRIMARY KEY,
    from_agent agent_type NOT NULL,
    to_agent agent_type,
    message_type VARCHAR(100) NOT NULL,
    content JSONB NOT NULL DEFAULT '{}',
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    processed_at TIMESTAMP WITH TIME ZONE,
    response JSONB DEFAULT '{}'
);

-- Indexes for agent communications
CREATE INDEX idx_agent_communications_to_agent ON agent_communications(to_agent);
CREATE INDEX idx_agent_communications_processed ON agent_communications(processed);
CREATE INDEX idx_agent_communications_timestamp ON agent_communications(timestamp DESC);
CREATE INDEX idx_agent_communications_message_type ON agent_communications(message_type);

-- Create views for common queries

-- Dashboard metrics view
CREATE VIEW v_current_metrics AS
SELECT DISTINCT ON (metric_type)
    metric_type,
    value,
    timestamp,
    metadata
FROM metrics
ORDER BY metric_type, timestamp DESC;

-- Recent alerts view
CREATE VIEW v_recent_alerts AS
SELECT 
    a.*,
    EXTRACT(EPOCH FROM (NOW() - a.created_at))/3600 as hours_ago
FROM alerts a
WHERE a.created_at >= NOW() - INTERVAL '24 hours'
ORDER BY a.created_at DESC;

-- Pending decisions view
CREATE VIEW v_pending_decisions AS
SELECT 
    d.*,
    EXTRACT(EPOCH FROM (NOW() - d.created_at))/3600 as hours_pending
FROM decisions d
WHERE d.status = 'pending'
ORDER BY d.created_at ASC;

-- Agent performance view
CREATE VIEW v_agent_performance AS
SELECT 
    agent_type,
    COUNT(*) as total_activities,
    COUNT(*) FILTER (WHERE success = true) as successful_activities,
    COUNT(*) FILTER (WHERE success = false) as failed_activities,
    AVG(duration_ms) as avg_duration_ms,
    MAX(timestamp) as last_activity
FROM agent_activities
WHERE timestamp >= NOW() - INTERVAL '24 hours'
GROUP BY agent_type;

-- Functions for common operations

-- Function to get metric trend
CREATE OR REPLACE FUNCTION get_metric_trend(
    p_metric_type metric_type,
    p_hours INTEGER DEFAULT 24
) RETURNS TABLE(
    timestamp TIMESTAMP WITH TIME ZONE,
    value DECIMAL(15,4)
) AS $$
BEGIN
    RETURN QUERY
    SELECT m.timestamp, m.value
    FROM metrics m
    WHERE m.metric_type = p_metric_type
      AND m.timestamp >= NOW() - (p_hours || ' hours')::INTERVAL
    ORDER BY m.timestamp ASC;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate metric statistics
CREATE OR REPLACE FUNCTION get_metric_stats(
    p_metric_type metric_type,
    p_hours INTEGER DEFAULT 24
) RETURNS TABLE(
    avg_value DECIMAL(15,4),
    min_value DECIMAL(15,4),
    max_value DECIMAL(15,4),
    std_dev DECIMAL(15,4),
    data_points BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        AVG(m.value)::DECIMAL(15,4),
        MIN(m.value)::DECIMAL(15,4),
        MAX(m.value)::DECIMAL(15,4),
        STDDEV(m.value)::DECIMAL(15,4),
        COUNT(*)
    FROM metrics m
    WHERE m.metric_type = p_metric_type
      AND m.timestamp >= NOW() - (p_hours || ' hours')::INTERVAL;
END;
$$ LANGUAGE plpgsql;

-- Insert sample data for testing
INSERT INTO metrics (metric_type, value, timestamp) VALUES
    ('revenue', 15000.00, NOW() - INTERVAL '2 hours'),
    ('revenue', 14500.00, NOW() - INTERVAL '1 hour'),
    ('revenue', 15200.00, NOW()),
    ('orders', 150, NOW() - INTERVAL '2 hours'),
    ('orders', 145, NOW() - INTERVAL '1 hour'),
    ('orders', 152, NOW()),
    ('churn_risk', 0.15, NOW() - INTERVAL '2 hours'),
    ('churn_risk', 0.16, NOW() - INTERVAL '1 hour'),
    ('churn_risk', 0.14, NOW()),
    ('delivery_delay', 2.5, NOW() - INTERVAL '2 hours'),
    ('delivery_delay', 2.8, NOW() - INTERVAL '1 hour'),
    ('delivery_delay', 2.3, NOW()),
    ('customer_satisfaction', 4.2, NOW() - INTERVAL '2 hours'),
    ('customer_satisfaction', 4.1, NOW() - INTERVAL '1 hour'),
    ('customer_satisfaction', 4.3, NOW());

-- Insert sample alerts
INSERT INTO alerts (title, description, severity, metric_type, current_value, agent_type) VALUES
    ('Revenue Drop Detected', 'Revenue has decreased by 15% compared to yesterday', 'high', 'revenue', 12750.00, 'observer'),
    ('High Churn Risk', 'Customer churn risk has increased above threshold', 'medium', 'churn_risk', 0.18, 'analyst');

-- Insert sample decisions
INSERT INTO decisions (title, description, scenarios, recommended_scenario, confidence_score, financial_impact, requires_approval, reasoning) VALUES
    ('Revenue Recovery Campaign', 'Launch promotional campaign to recover revenue', 
     '[{"name": "15% Discount Campaign", "description": "Offer 15% discount to all customers", "confidence_score": 0.75, "risk_score": 0.3}]',
     '15% Discount Campaign', 0.75, -5000.00, true, 
     'Based on historical data, promotional campaigns have shown 75% success rate in revenue recovery scenarios.');

-- Grant permissions (adjust as needed for your setup)
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO agentic_ai_user;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO agentic_ai_user;